version: "3.8"
services:
  db:
    container_name: db-mysql-container
    image: mysql
    environment:
      MYSQL_DATABSE: test_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306" # for development tools (ex.dbeaver)
    expose:
      - "3406" # to communicate with internal container.
    volumes:
      - ./volumes/db/conf.d:/db/conf.d
      - ./volumes/db/data:/db/data
      - ./volumes/db/initdb.d:/db/initdb.d

  proxy:
    container_name: proxy-nginx-container
    image: nginx
    ports:
      - "80:80" # for user who connecting by browser using http.
      - "443:443" # for user who connecting by browser using https.
      - "8080:8080" # for development tools (TODO)
    expose:
      - "9100" # to communicate with internal container.( to http web container )
      - "9101" # to communicate with internal container.( to https web container )
      - "9102" # to communicate with internal container.( to test web container )
    volumes:
      - ./volumes/proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/proxy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    container_name: web-nginx-container
    image: nginx
#    ports:
#      - "9100:9100" # for http development tools. (ex.postman)
#      - "9101:9101" # for https development tools. (ex.postman)
#      - "9102:9102" # for test development tools. (ex.postman)
    expose:
      - "9100" # to communicate with internal container(http).
      - "9101" # to communicate with internal container(https).
      - "9102" # to communicate with internal container(test).
    volumes:
      - ./volumes/web/source:/source
      - ./volumes/web/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/web/nginx/html/yu.html:/usr/share/nginx/html/yu.html
      - ./volumes/web/nginx/html/kim.html:/usr/share/nginx/html/kim.html
   
    depends_on:
      - db
